// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nryaxydlzsqjomogefjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yeWF4eWRsenNxam9tb2dlZmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTI1MDAsImV4cCI6MjA2MzU2ODUwMH0.rrkaQ_CbzekFJEuuP2IPT3pKpWAoAndpyxJEmkFdcag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});